# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20171125_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
