# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated_by',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
