# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20171125_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attached',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
