# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_attached'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by_id', models.IntegerField()),
                ('attached', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
