# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='uploaded_by_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
