# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20171126_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='uploaded_by_id',
            field=models.IntegerField(),
        ),
    ]
