# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20171126_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploads',
            old_name='uploaded_by_id',
            new_name='uploaded_by_email',
        ),
    ]
