# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20171126_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='uploaded_by_email',
            field=models.CharField(max_length=50),
        ),
    ]
