# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20171126_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='uploaded_by_email',
        ),
        migrations.AddField(
            model_name='uploads',
            name='uploaded_by_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
