# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 02:29
from __future__ import unicode_literals

from django.db import migrations
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20171126_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attached',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=task.models.IntegerRangeField(),
        ),
    ]
